export default [
    {
      id: "1",
      categoryId: "1",
      name: "Affordances Table",
      description: "Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.",
      price: 823,
      image: "/uploads/1.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    },
    {
      id: "2",
      categoryId: "1",
      name: "Afteroom Barstool",
      description: "Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.",
      price: 953,
      image: "/uploads/2.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    },
    {
      id: "3",
      categoryId: "4",
      name: "Beer Foamer",
      description: "Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced.",
      price: 764,
      image: "/uploads/3.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    },
    {
      id: "4",
      categoryId: "5",
      name: "BIT Side Table",
      description: "Embodying the raw, wayward spirit of rock ‘n’ roll, the Kilburn portable active stereo speaker takes the unmistakable look and sound of Marshall, unplugs the chords, and takes the show on the road. Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.",
      price: 128,
      image: "/uploads/4.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    },
    {
      id: "5",
      categoryId: "3",
      name: "Boro Wall Shelf",
      description: "Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.",
      price: 674,
      image: "/uploads/5.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    },
    {
      id: "6",
      categoryId: "2",
      name: "Bottle Grinder",
      description: "Embodying the raw, wayward spirit of rock ‘n’ roll, the Kilburn portable active stereo speaker takes the unmistakable look and sound of Marshall, unplugs the chords, and takes the show on the road. Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.",
      price: 141,
      image: "/uploads/6.jpg",
      Height: "37-45″",
      Width: "24″",
      Wheels: "12″ air / wide track slick tread",
      Weight: "20 LBS",
      Folded: "32.5″L x 18.5″W x 16.5″H",
      Frame: "Aluminum",
      StandUp: "35″L x 24″W x 37-45″H(front to back wheel)"
    }
  ]
  