//List of actions constants

//Fetchiing products
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

//Load more products
export const LOAD_MORE_PRODUCTS_START = 'LOAD_MORE_PRODUCTS_START';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_FAILURE = 'LOAD_MORE_PRODUCTS_FAILURE';

//Fetch product by id
export const FETCH_PRODUCTS_BY_ID_START = 'FETCH_PRODUCTS_BY_ID_START';
export const FETCH_PRODUCTS_BY_ID_SUCCESS = 'FETCH_PRODUCTS_BY_ID_SUCCESS';
export const FETCH_PRODUCTS_BY_ID_FAILURE = 'FETCH_PRODUCTS_BY_ID_FAILURE';

//Adding and removing product from basket
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET';

//Cleaning basket
export const CLEAN_BASKET = 'CLEAN_BASKET';

